development:
  adapter: postgresql
  database: blog_development
  username:
  password: "m200266756"

test:
  adapter: postgresql
  database: blog_test
  username:
  password: "m200266756"

production:
  adapter: postgresql
  database: blog_production
  username:
  password: "m200266756"
